name: Build sneaky-helper wheel
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - run: echo "Initiating sneaky-helper build..."
            - run: |
                  $(realpath `which python3`) -m venv .venv;
                  source .venv/bin/activate;
                  python -m pip install --upgrade pip setuptools wheel;
                  pip install -e .[build,test];
                  python -m build;
            - run: echo "sneaky-helper build complete..."
